### ISSUE TITLE
Not Appearing Somtimes In 2v2

### ISSUE THREAD

**Issue by nfgallimore** [stako/sArena#40]
Bars do not show up sometimes in 2v2. Not sure what variables reproduce this.

**Comment by stako** [comment]
Does it happen when sArena is the only addon enabled? If no, which addon is causing the conflict?

**Comment by xecutable** [comment]
I think it happens more often when you join the arena late. My partner and I have been trying to see when it exactly happens. No, we have BigDebuffs and OmniCC usually most pvpers have those. 

Spoke with other guildies they have the same issue and they have to reload. Is there a way to see what may cause conflict?

**Comment by stako** [comment]
If it's not happening when sArena is the only addon enabled, you've just got to gradually enable your other addons a few at a time (or even just 1 at a time) until the issue arises again. Enable/disable to narrow it down to 1 addon - that's the conflicting one.

Also worth noting that it is intentional (on Blizzard's part, not mine) that the arena frames will not appear during the preparation phase until your entire party has zoned in.

**Comment by xecutable** [comment]
Right. One of us sees the team, the other does not and has to reload. I'll start testing tomorrow and try to enable addons one by one as it must be something both of us have (as well as other people in the guild).

**Comment by stako** [comment]
Looks like this happens when zoning into the arena while in combat. Will fix in the near future.

In the meantime you may want to leave combat before zoning in, or reload UI after zoning in.

**Comment by nfgallimore** [comment]
Thanks @stako
